import Foundation

/// Renders a report as Markdown, for sharing and export.
///
/// Plain text on purpose: a debate report that can be pasted into an email,
/// a Google Doc or a teacher's feedback form gets used. A proprietary
/// bundle does not.
public enum ReportFormatter {

    public static func markdown(_ report: DebateReport) -> String {
        var lines: [String] = []

        lines.append("# \(report.topic)")
        lines.append("")
        lines.append("*\(report.format.summary) · \(formatted(report.generatedAt))*")
        lines.append("")

        // Verdict
        lines.append("## Verdict")
        lines.append("")
        if let winner = report.verdict.winner {
            lines.append("**\(report.transcript.name(of: winner))** — \(report.verdict.confidenceLabel.lowercased()), margin \(number(report.verdict.margin)).")
        } else {
            lines.append("**Draw** — \(report.verdict.confidenceLabel.lowercased()), margin \(number(report.verdict.margin)).")
        }
        lines.append("")
        lines.append(report.verdict.rationale)
        lines.append("")

        // Scores
        lines.append("## Scores")
        lines.append("")
        let nameA = report.transcript.name(of: .a)
        let nameB = report.transcript.name(of: .b)
        lines.append("| Dimension | \(nameA) | \(nameB) |")
        lines.append("| --- | ---: | ---: |")
        for dimension in Dimension.allCases {
            let a = number(report.scorecard(.a).value(for: dimension))
            let b = number(report.scorecard(.b).value(for: dimension))
            lines.append("| \(dimension.title) | \(a) | \(b) |")
        }
        lines.append("| **Overall** | **\(number(report.scorecard(.a).overall))** | **\(number(report.scorecard(.b).overall))** |")
        lines.append("")

        // Per speaker
        for speaker in report.speakers {
            lines.append("## \(speaker.name)")
            lines.append("")
            lines.append("\(speaker.stats.turns) turns · \(speaker.stats.words) words · \(speaker.stats.claims) statements · \(speaker.stats.sourcedClaims) sourced · \(speaker.stats.fallacies) reasoning flags")
            lines.append("")

            if let best = speaker.bestArgument {
                lines.append("**Strongest moment.** \u{201C}\(best.quote)\u{201D}")
                lines.append("")
                lines.append(best.reason)
                lines.append("")
            }
            if let weakest = speaker.weakestArgument {
                lines.append("**Weakest moment.** \u{201C}\(weakest.quote)\u{201D}")
                lines.append("")
                lines.append(weakest.reason)
                lines.append("")
            }

            let negatives = speaker.findings.negativeOnly
            if !negatives.isEmpty {
                lines.append("### Findings")
                lines.append("")
                for finding in negatives {
                    lines.append("- **\(finding.title)** (\(finding.severity.title)) — \u{201C}\(finding.quote)\u{201D}")
                    lines.append("  \(finding.detail)")
                    if !finding.coaching.isEmpty {
                        lines.append("  *\(finding.coaching)*")
                    }
                }
                lines.append("")
            }

            if !speaker.missedOpportunities.isEmpty {
                lines.append("### Left unanswered")
                lines.append("")
                for highlight in speaker.missedOpportunities {
                    lines.append("- \u{201C}\(highlight.quote)\u{201D}")
                }
                lines.append("")
            }

            if !speaker.suggestions.isEmpty {
                lines.append("### Do this next time")
                lines.append("")
                for (index, suggestion) in speaker.suggestions.enumerated() {
                    lines.append("\(index + 1). \(suggestion)")
                }
                lines.append("")
            }
        }

        if !report.sharedGround.isEmpty {
            lines.append("## Common ground")
            lines.append("")
            for line in report.sharedGround {
                lines.append("- \(line)")
            }
            lines.append("")
        }

        lines.append("## Transcript")
        lines.append("")
        for turn in report.transcript.turns {
            lines.append("**\(report.transcript.name(of: turn.side))** — \(turn.text)")
            lines.append("")
        }

        lines.append("## What this report is not")
        lines.append("")
        for caveat in report.caveats {
            lines.append("- \(caveat)")
        }
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("Generated by Veritas.")

        return lines.joined(separator: "\n")
    }

    static func number(_ value: Double) -> String {
        String(format: "%.0f", value)
    }

    static func formatted(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .short
        return formatter.string(from: date)
    }

    /// `mm:ss` for the replay timeline.
    public static func timestamp(_ offset: TimeInterval) -> String {
        let total = Int(offset.rounded())
        return String(format: "%d:%02d", total / 60, total % 60)
    }
}
